=== ikaren/auto-man/auto-man-parent/auto-man-parser/src/main/resources/META-INF/automan.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns="http://org.jason.automan/schema/automan"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://org.jason.automan/schema/automan">

    <xsd:element name="automan">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="project" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="project">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="datasource" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="dubbo" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="log4j-elk" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="data-table" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="project-name" type="xsd:string" use="required"/>
            <xsd:attribute name="project-dir" type="xsd:string" use="required"/>
            <xsd:attribute name="package-name" type="xsd:string" use="required"/>
            <xsd:attribute name="template-root" type="xsd:string" default="classpath:/template" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="datasource">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="database-config" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="database-config">
        <xsd:complexType>
            <xsd:attribute name="env" type="environment" use="required"/>
            <xsd:attribute name="db-name" type="xsd:string" use="required"/>
            <xsd:attribute name="host" type="xsd:string" default="127.0.0.1" use="required"/>
            <xsd:attribute name="port" type="xsd:int" default="3306"/>
            <xsd:attribute name="username" type="xsd:string" default="root" use="required"/>
            <xsd:attribute name="password" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="dubbo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="dubbo-config" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="service-name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="dubbo-config">
        <xsd:complexType>
            <xsd:attribute name="env" type="environment" use="required"/>
            <xsd:attribute name="port" type="xsd:int" default="20880" use="required"/>
            <xsd:attribute name="zk-address" type="xsd:string" default="127.0.0.1:2181" use="required"/>
            <xsd:attribute name="group" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="log4j-elk">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="log4j-elk-cfg" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="log4j-elk-cfg">
        <xsd:complexType>
            <xsd:attribute name="env" type="environment" use="required"/>
            <xsd:attribute name="port" type="xsd:int" default="8890" use="required"/>
            <xsd:attribute name="host" type="xsd:string" default="127.0.0.1" use="required"/>
            <xsd:attribute name="reconn-delay" type="xsd:long" default="50000" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="data-table">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="column" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string"/>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="desc" type="xsd:string" use="optional"/>
            <xsd:attribute name="class-name" type="xsd:string" use="required"/>
            <xsd:attribute name="is-domain" type="xsd:boolean" default="true" use="required"/>
            <xsd:attribute name="binding-domain" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="column">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="jdbcType" type="jdbcType" use="required"/>
            <xsd:attribute name="length" type="xsd:integer"/>
            <xsd:attribute name="notNull" type="xsd:boolean"/>
            <xsd:attribute name="unique" type="xsd:boolean"/>
            <xsd:attribute name="default-value" type="xsd:string"/>
            <xsd:attribute name="desc" type="xsd:string"/>
            <xsd:attribute name="property" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <!-- simpleType -->

    <!-- jdbcType from mybatis -->
    <xsd:simpleType name="jdbcType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="FLOAT"/>
            <xsd:enumeration value="CHAR"/>
            <xsd:enumeration value="TIMESTAMP"/>
            <xsd:enumeration value="TINYINT"/>
            <xsd:enumeration value="VARCHAR"/>
            <xsd:enumeration value="DOUBLE"/>
            <xsd:enumeration value="INTEGER"/>
            <xsd:enumeration value="BIGINT"/>
            <xsd:enumeration value="DECIMAL"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="environment">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="PROD"/>
            <xsd:enumeration value="BETA"/>
            <xsd:enumeration value="ALPHA"/>
            <xsd:enumeration value="DEV"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="property">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="value" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== ikaren/auto-man/auto-man-parent/auto-man-parser/src/main/resources/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<automan xmlns="http://org.jason.automan/schema/automan"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://org.jason.automan/schema/automan http://org.jason.automan/schema/automan/automan.xsd">

    <project id="testProject" project-name="tags" project-dir="/Users/yuqingxia/ci-test"
             package-name="com.hans.jhd.domain.tags">
        <datasource id="datasourceConfig">
            <database-config env="PROD" db-name="prod_tags" host="127.0.0.1" username="root" password="123"/>
            <database-config env="BETA" db-name="beta_tags" host="127.0.0.1" username="root" password="123"/>
            <database-config env="ALPHA" db-name="alpha_tags" host="127.0.0.1" username="root" password="123"/>
            <database-config env="DEV" db-name="dev_tags" host="127.0.0.1" username="root" password="123"/>
        </datasource>

        <dubbo id="prodDubboConfig" service-name="domain-tags">
            <dubbo-config env="PROD" port="20880" zk-address="127.0.0.1:2181" group="daq.prod"/>
            <dubbo-config env="BETA" port="20880" zk-address="127.0.0.1:2181" group="daq.beta"/>
            <dubbo-config env="ALPHA" port="20880" zk-address="127.0.0.1:2181" group="daq.alpha"/>
            <dubbo-config env="DEV" port="20880" zk-address="127.0.0.1:2181" group="daq.dev"/>
        </dubbo>

        <log4j-elk id="log4jForELK">
            <log4j-elk-cfg env="PROD" port="8890" host="127.0.0.1" reconn-delay="50000"/>
            <log4j-elk-cfg env="BETA" port="8890" host="127.0.0.1" reconn-delay="50000"/>
            <log4j-elk-cfg env="ALPHA" port="8890" host="127.0.0.1" reconn-delay="50000"/>
            <log4j-elk-cfg env="DEV" port="8890" host="127.0.0.1" reconn-delay="50000"/>
        </log4j-elk>

        <table id="reservationTable" name="reservation" desc="预约表" class-name="Reservation" is-domain="true" binding-domain="Reservation">
            <columns>
                <column name="id" jdbcType="BIGINT" property="id" length="10" notNull="true" unique="true"
                        default-value="1"/>
                <column name="name" jdbcType="VARCHAR" property="name"/>
                <column name="create_at" jdbcType="TIMESTAMP" property="createAt"/>
                <column name="update_at" jdbcType="TIMESTAMP" property="updateAt"/>
            </columns>
        </table>

        <table id="traceTable" name="reservation_trace" desc="预约跟踪表" class-name="ReservationTrace" is-domain="true" binding-domain="ReservationTrace">
            <columns>
                <column name="id" jdbcType="BIGINT" property="id" length="10" notNull="true" unique="true"
                        default-value="1"/>
                <column name="name" jdbcType="VARCHAR" property="name"/>
                <column name="create_at" jdbcType="TIMESTAMP" property="createAt"/>
                <column name="update_at" jdbcType="TIMESTAMP" property="updateAt"/>
            </columns>
        </table>

        <table id="reportTable" name="report" desc="报告表" class-name="Report" is-domain="true" binding-domain="Report">
            <columns>
                <column name="id" jdbcType="BIGINT" property="id" length="10" notNull="true" unique="true"
                        default-value="1"/>
                <column name="name" jdbcType="VARCHAR" property="name"/>
                <column name="create_at" jdbcType="TIMESTAMP" property="createAt"/>
                <column name="update_at" jdbcType="TIMESTAMP" property="updateAt"/>
            </columns>
        </table>
    </project>


</automan>

=== ikaren/auto-man/auto-man-parent/auto-man-startup/src/main/resources/reservation-demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<automan xmlns="http://org.jason.automan/schema/automan"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://org.jason.automan/schema/automan http://org.jason.automan/schema/automan/automan.xsd">

    <project id="testProject" project-name="reservation" project-dir="/Users/yuqingxia/ci-test"
             package-name="com.hans.jhd.service.reservation" template-root="classpath:/template">
        <datasource id="datasourceConfig">
            <database-config env="PROD" db-name="prod_tags" host="127.0.0.1" port="3306" username="root"
                             password="123"/>
            <database-config env="BETA" db-name="beta_tags" host="127.0.0.1" port="3306" username="root"
                             password="123"/>
            <database-config env="ALPHA" db-name="alpha_tags" host="127.0.0.1" port="3306" username="root"
                             password="123"/>
            <database-config env="DEV" db-name="dev_tags" host="127.0.0.1" port="3306" username="root" password="123"/>
        </datasource>

        <dubbo id="prodDubboConfig" service-name="domain-tags">
            <dubbo-config env="PROD" port="20880" zk-address="127.0.0.1:2181" group="daq.prod"/>
            <dubbo-config env="BETA" port="20880" zk-address="127.0.0.1:2181" group="daq.beta"/>
            <dubbo-config env="ALPHA" port="20880" zk-address="127.0.0.1:2181" group="daq.alpha"/>
            <dubbo-config env="DEV" port="20880" zk-address="127.0.0.1:2181" group="daq.dev"/>
        </dubbo>

        <log4j-elk id="log4jForELK">
            <log4j-elk-cfg env="PROD" port="8890" host="127.0.0.1" reconn-delay="50000"/>
            <log4j-elk-cfg env="BETA" port="8890" host="127.0.0.1" reconn-delay="50000"/>
            <log4j-elk-cfg env="ALPHA" port="8890" host="127.0.0.1" reconn-delay="50000"/>
            <log4j-elk-cfg env="DEV" port="8890" host="127.0.0.1" reconn-delay="50000"/>
        </log4j-elk>

        <data-table id="reservationTable" name="reservation" desc="预约表" class-name="Reservation" is-domain="true"
               binding-domain="Reservation">
            <column name="tel_num" jdbcType="VARCHAR" property="telNum"/>
            <column name="account_id" jdbcType="BIGINT" property="accountId"/>
            <column name="reservation_status" jdbcType="INTEGER" property="reservationStatus"/>
        </data-table>

        <data-table id="traceTable" name="reservation_trace" desc="预约跟踪表" class-name="ReservationTrace" is-domain="true"
               binding-domain="ReservationTrace">
            <column name="reservation_id" jdbcType="BIGINT" property="reservationId"/>
            <column name="process" jdbcType="VARCHAR" property="process"/>
        </data-table>

        <data-table id="reportTable" name="report" desc="报告表" class-name="Report" is-domain="true" binding-domain="Report">
            <column name="reservation_id" jdbcType="BIGINT" property="reservationId"/>
            <column name="url" jdbcType="VARCHAR" property="url"/>
            <column name="time" jdbcType="TIMESTAMP" property="time"/>
        </data-table>
    </project>


</automan>
